/// Flutter icons FlutterIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcons
///      fonts:
///       - asset: fonts/FlutterIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterIcons {
  FlutterIcons._();

  static const _kFontFam = 'FlutterIcons';

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe871, fontFamily: _kFontFam);
  static const IconData back = IconData(0xe879, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xf1de, fontFamily: _kFontFam);
}
